### ISSUE TITLE
Add in Ubuntu specific page

### ISSUE THREAD

**Issue by spences10** [spences10/cheat-sheets#1046]
One thing to go on there will be removing snap firefox and replacing with apt version

```bash
snap list
sudo snap remove firefox
sudo apt install firefox
snap list
```

**Comment by ghostdevv** [comment]
snap isn't specific to ubuntu and since there isn't a search bar that searches entire site it might make more sense to make a snap page

**Comment by spences10** [comment]
I was looking at this the other day and feel that most of the stuff is covered in the Linux sheet to be honest.

About searching the entire site, I did look into adding in the headers but I think MDsveX still doesn't support it.

I'll close this, thanks for your comment @ghostdevv 🙌
