### ISSUE TITLE
Gitignore

### ISSUE THREAD

**Issue by eclectic-coding** [spences10/cheat-sheets#222]
Scott,
I have been experimenting with generating `.gitignore` files from the command line and I thought you might be interested in this one. I have been using the [gitignore.io API](https://docs.gitignore.io/install/command-line). 

To set up on Linux ZSH:
```sh
echo "function gi() { curl -sLw "\n" https://www.gitignore.io/api/\$@ ;}" >> \
~/.zshrc && source ~/.zshrc
```
Then inside your project:
```
gi linux,visualstudiocode,node >> ./.gitignore 
```
Thats pretty much it. Lots of different languages supported.

**Comment by spences10** [comment]
Oh hey @eclectic-coding, I've just switched over to using ZSH on the mac so I can give this a go!

I'll happily accept a PR is you want to make your own PR or I can add with a credit to this issue

**Comment by eclectic-coding** [comment]
Out of town this weekend but I will submit a PR the first of the week.
